username: username
password: password 
phone_number: phone_number

position: position

location: location

resume_folder: complete resume_folder with file name

job_details_folder: complete job_details_folder