username: afeefkhan99@gmail.com
password: restorer123 
phone_number: 0504221039

position: python developer

location: united arab emirates

resume_folder: C:\Users\afeef\Desktop\My folder\CV\Automation\Afeef CV.pdf

job_details_folder: C:\Users\afeef\Desktop\My folder\Coding TP\Py automation\linkedin